# Generated by Django 4.2.5 on 2023-09-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('decricao_curta', models.TextField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/&m/')),
                ('slug', models.SlugField(unique=True)),
                ('preco', models.FloatField()),
            ],
        ),
    ]
