# Generated by Django 4.2.5 on 2023-09-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
