# Generated by Django 4.2.5 on 2023-09-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_rename_decricao_curta_produto_descricao_curta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
