# Generated by Django 4.2.5 on 2023-09-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sobrenome',
            field=models.CharField(default='sobrenome', max_length=255),
            preserve_default=False,
        ),
    ]
