# Generated by Django 4.2.5 on 2023-09-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_produto_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='sobrenome',
        ),
    ]
